# -*- coding: utf-8 -*-
"""mckinsey.ipynb

Automatically generated by Colab.

Original file is located at
    https://colab.research.google.com/drive/1dO3D5zxBpYiUeJjj7G77fsPi9IJ0nA_H
"""

import seaborn as sns
import pandas as pd
import numpy as np
import matplotlib.pyplot as plt

!gdown 1VcLR7TKzJlEyNJIZtD3LL14JU1SMfL5t

data = pd.read_csv('mckinsey.csv')
data.head(6)

data_df=pd.DataFrame(data)

"""Initial Analysis"""

data_df.columns

"""We have the below mentioned coloumn
Country
Year
Population
Continent
Life Exp
Gdp Capita
"""

data_df.dtypes

"""The Values present in the coloumns are as of below mentioned types
Country => object
Year=> Int
Population => Int
Continent => Object
Life_exp => Float
GDP_CAP => Float
"""

data_df.isna().value_counts()

"""There is no null values"""

data_df.duplicated().value_counts()

"""Since everything is false there are no duplicates present in the data set."""

data_df['continent'].unique()

"""we have 5 different continents in the data

1) Analysis with respect to the Continent
"""

continentdata_df = data_df.groupby('continent')[['life_exp', 'gdp_cap', 'population']].agg({'life_exp': 'mean', 'gdp_cap': 'mean','population': 'mean' })
continentdata_df

"""Population in each continent"""

plt.figure(figsize=(12,6))
sns.barplot(data=continentdata_df,x='continent', y='population')
plt.xlabel("Continents")
plt.ylabel("Population")
plt.title("Population per continent")
plt.show()

"""Asia has the highest average population which is about 77 million, thirty-eight thousand, seven hundred twenty.

Continent to Life Expectancy analysis
"""

plt.figure(figsize=(12,6))
sns.barplot(data=continentdata_df,x='continent', y='life_exp')
plt.xlabel("Continents")
plt.ylabel("Life Expectancy")
plt.title("Continent to Life Expectancy Graph")
plt.show()

"""We can say that the Highest Average Life expectancy is in Oceania which is about 74.326208

Max GDP breakdown in each continent
"""

plt.figure(figsize=(12,6))
sns.barplot(data=continentdata_df,x='continent', y='gdp_cap')
plt.xlabel("Continents")
plt.ylabel("GDP per Capita")
plt.title("Continent to GDP Graph")
plt.show()

"""Highest Average GDP is in Oceania which is about 18621

2) Analysis done on each continent

Analysis on Asia
"""

countryasia_df = data_df.loc[data_df['continent']=='Asia']
countryasia_df.head(5)

countryasia_df['country'].unique()

"""We have these many country in Asia"""

countryasiaa_df=countryasia_df.groupby('country')[['life_exp', 'gdp_cap', 'population']].aggregate({'life_exp': 'mean', 'gdp_cap': 'mean','population': 'mean' })
countryasiaa_df.head(5)

"""Top 10 Highest Populated country in Asia"""

t10pofcasiaa_df = countryasiaa_df.sort_values(by='population', ascending=False).head(10)
plt.figure(figsize=(12,6))
sns.barplot(data=t10pofcasiaa_df,x='country', y='population')
plt.xlabel("Continents")
plt.ylabel("Population")
plt.title("Population in Each Country")
plt.show()

"""These are the countries with top population.

Highest Life Expectancy in Asia by country wise top 10
"""

t10poflifeexpasia_df = countryasiaa_df.sort_values(by='life_exp', ascending=False).head(10)
print(t10poflifeexpasia_df)
plt.figure(figsize=(12,6))
sns.barplot(data=t10pofcasiaa_df,x='country', y='life_exp')
plt.xlabel("Continents")
plt.ylabel("life Expectancy")
plt.title("Top 10 Countries having the Highest Average life expectancy in Asia")
plt.show()

"""We can see that Japan has the highest life expectancy

Highest life expectancy according the top 10 countries with highest population
"""

t10pofclifeexpasia_df = t10pofcasiaa_df.sort_values(by='life_exp', ascending=False).head(10)
plt.figure(figsize=(12,6))
sns.barplot(data=t10pofclifeexpasia_df,x='country', y='life_exp')
plt.xlabel("Continents")
plt.ylabel("life Expectancy")
plt.title("Top 10 Countries having the Highest Average life expectancy in Asia")
plt.show()

"""We can say that japan has the highest life expectancy even though the population is very less where as china stands at third position in terms of life expectancy eventhough
it has the highest no of population

Highest GDP in Asia by country wise top 10
"""

t10pofgdpofasia_df = countryasiaa_df.sort_values(by='gdp_cap', ascending=False).head(10)
print(t10pofgdpofasia_df)
plt.figure(figsize=(12,6))
sns.barplot(data=t10pofgdpofasia_df,x='country', y='gdp_cap')
plt.xlabel("Continents")
plt.ylabel("GDP per Capita")
plt.title("Top 10 countires having the highest GDP per capita in Asia")
plt.show()

"""Kuwait has the highest GDP which is about 113523

Highest Average GDP according the top 10 countries with highest population
"""

t10pofcgdpofasia_df = t10pofcasiaa_df.sort_values(by='gdp_cap', ascending=False).head(10)
print(t10pofcgdpofasia_df)
plt.figure(figsize=(12,6))
sns.barplot(data=t10pofcgdpofasia_df,x='country', y='gdp_cap')
plt.xlabel("Continents")
plt.ylabel("GDP per Capita")
plt.title("Top 10 countires having the highest GDP per capita in Asia")
plt.show()

"""In the countries with highest population we can see that japan has the highest GDP that is about 31656

Analysis on America
"""

countryamerica_df = data_df.loc[data_df['continent']=='Americas']
countryamerica_df.head(5)

countryamerica_df['country'].unique()

"""we have these many countries in America"""

countryamericaa_df=countryamerica_df.groupby('country')[['life_exp', 'gdp_cap', 'population']].aggregate({'life_exp': 'mean', 'gdp_cap': 'mean','population': 'mean' })
countryamericaa_df.head(5)

"""Top 10 Highest Populated country in America"""

t10pofcamerica_df = countryamericaa_df.sort_values(by='population', ascending=False).head(10)
print(t10pofcamerica_df)
plt.figure(figsize=(12,6))
sns.barplot(data=t10pofcamerica_df,x='country', y='population')
plt.xlabel("Continents")
plt.ylabel("Population")
plt.title("Population in Each Country across America")
plt.show()

"""United states has the highest population which is about 228 million, two hundred eleven thousand, two hundred.

Highest Average life expectancy in America Top 10
"""

t10poflifeexpamerica_df = countryamericaa_df.sort_values(by='life_exp', ascending=False).head(10)
print(t10poflifeexpamerica_df)
plt.figure(figsize=(12,6))
sns.barplot(data=t10poflifeexpamerica_df,x='country', y='life_exp')
plt.xlabel("Continents")
plt.ylabel("life Expectancy")
plt.title("Top 10 Countries having the Highest Average life expectancy in America")
plt.show()

"""We can see that canada has the highest life expectancy which is about 74.90

Highest Average life expectancy in Top 10 Highest populated country in America
"""

t10poflifeexpamerica_df = t10pofcamerica_df.sort_values(by='life_exp', ascending=False).head(10)
print(t10poflifeexpamerica_df)
plt.figure(figsize=(12,6))
sns.barplot(data=t10poflifeexpamerica_df,x='country', y='life_exp')
plt.xlabel("Continents")
plt.ylabel("life Expectancy")
plt.title("Highest Average Life expectancy in Top 10 highly populated country in America")
plt.show()

"""Highest GDP in America Top 10"""

t10pofgdpamerica_df = countryamericaa_df.sort_values(by='gdp_cap', ascending=False).head(10)
print(t10pofgdpamerica_df)
plt.figure(figsize=(12,6))
sns.barplot(data=t10pofgdpamerica_df,x='country', y='gdp_cap')
plt.xlabel("Continents")
plt.ylabel("GDP per Capita")
plt.title("Top 10 Countries having the Highest Average GDP in America")
plt.show()

"""United States has the highest average GDP per capita that is 26261.1

Highest Average GDP in Highly populated Country in America
"""

t10pofcgdpamerica_df = t10pofcamerica_df.sort_values(by='gdp_cap', ascending=False).head(10)
print(t10pofcgdpamerica_df)
plt.figure(figsize=(12,6))
sns.barplot(data=t10pofcgdpamerica_df,x='country', y='gdp_cap')
plt.xlabel("Continents")
plt.ylabel("GDP per Capita")
plt.title("Top 10 Countries having the Highest Average GDP in America")
plt.show()

"""Analysis on Europe"""

countryeurope_df = data_df.loc[data_df['continent']=='Europe']
countryeurope_df.head(5)

countryeurope_df['country'].unique()

"""We have these many countries in Europe"""

countryeuropee_df=countryeurope_df.groupby('country')[['life_exp', 'gdp_cap', 'population']].aggregate({'life_exp': 'mean', 'gdp_cap': 'mean','population': 'mean' })
countryeuropee_df.head(5)

"""Top 10 Highly Populated country in Europe"""

t10pofceurope_df = countryeuropee_df.sort_values(by='population', ascending=False).head(10)
print(t10pofceurope_df)
plt.figure(figsize=(12,6))
sns.barplot(data=t10pofceurope_df,x='country', y='population')
plt.xlabel("Continents")
plt.ylabel("Population")
plt.title("Population in Each Country across Europe")
plt.show()

"""We can Say that Germany is the most highly populated Country in Europe

Highest Average Life Expectancy in Europe
"""

t10poflifeexpeurope_df = countryeuropee_df.sort_values(by='life_exp', ascending=False).head(10)
print(t10poflifeexpeurope_df)
plt.figure(figsize=(12,6))
sns.barplot(data=t10poflifeexpeurope_df,x='country', y='life_exp')
plt.xlabel("Continents")
plt.ylabel("life Expectancy")
plt.title("Top 10 Countries having the Highest Average life expectancy in Europe")
plt.show()

"""Iceland has the highest average life expectancy of about 76.511417

Average life Expectancy of highly populated countries in Europe
"""

t10poflifeexpeurope_df = t10pofceurope_df.sort_values(by='life_exp', ascending=False).head(10)
print(t10poflifeexpeurope_df)
plt.figure(figsize=(12,6))
sns.barplot(data=t10poflifeexpeurope_df,x='country', y='life_exp')
plt.xlabel("Continents")
plt.ylabel("life Expectancy")
plt.title("Highest Average Life expectancy in Top 10 highly populated country in Europe")
plt.show()

"""Among the highest populated country netherland has the highest average life expectancy that is about 75.6

Top 10 Highest GDP in Europe
"""

t10pofgdpeurope_df = countryeuropee_df.sort_values(by='gdp_cap', ascending=False).head(10)
print(t10pofgdpeurope_df)
plt.figure(figsize=(12,6))
sns.barplot(data=t10pofgdpeurope_df,x='country', y='gdp_cap')
plt.xlabel("Continents")
plt.ylabel("GDP per Capita")
plt.title("Top 10 Countries having the Highest Average GDP in Europe")
plt.show()

"""We can see that Switzerland has the highest average GDP per capita of about 27074.334405

Highest GDP in highly populated countries of Europe
"""

t10pofcgdpeurope_df = t10pofceurope_df.sort_values(by='gdp_cap', ascending=False).head(10)
print(t10pofcgdpeurope_df)
plt.figure(figsize=(12,6))
sns.barplot(data=t10pofcgdpeurope_df,x='country', y='gdp_cap')
plt.xlabel("Continents")
plt.ylabel("GDP per Capita")
plt.title("Top 10 Countries having the Highest Average GDP in Europe")
plt.show()

"""We can see among the highest populated areas Netherland has the highest GDP which is about 21748

Analysis on Africa
"""

countryafrica_df = data_df.loc[data_df['continent']=='Africa']
countryafrica_df.head(5)

countryafrica_df['country'].unique()

"""These are the countries in Africa"""

countryafricaa_df=countryafrica_df.groupby('country')[['life_exp', 'gdp_cap', 'population']].aggregate({'life_exp': 'mean', 'gdp_cap': 'mean','population': 'mean' })
countryafricaa_df.head(5)

"""Top 10 highly populated country in Africa"""

t10pofcafrica_df = countryafricaa_df.sort_values(by='population', ascending=False).head(10)
print(t10pofcafrica_df)
plt.figure(figsize=(12,6))
sns.barplot(data=t10pofcafrica_df,x='country', y='population')
plt.xlabel("Continents")
plt.ylabel("Population")
plt.xticks(rotation=30)
plt.title("Population in Each Country across Africa")
plt.show()

"""We can see that Nigeria has the highest average population about Seventy-three million, seven hundred eight thousand, twenty.

Highest Average Life expectancy
"""

t10poflifeexpafrica_df = countryafricaa_df.sort_values(by='life_exp', ascending=False).head(10)
print(t10poflifeexpafrica_df)
plt.figure(figsize=(12,6))
sns.barplot(data=t10poflifeexpafrica_df,x='country', y='life_exp')
plt.xlabel("Continents")
plt.ylabel("life Expectancy")
plt.title("Top 10 Countries having the Highest Average life expectancy in Africa")
plt.show()

"""Highest life expectancy is in the Reunion country of africa which is about 66.644250

Average life expectancy of highly Populated country in Africa
"""

t10poflifeexpafrica_df = t10pofcafrica_df.sort_values(by='life_exp', ascending=False).head(10)
print(t10poflifeexpafrica_df)
plt.figure(figsize=(12,6))
sns.barplot(data=t10poflifeexpafrica_df,x='country', y='life_exp')
plt.xlabel("Continents")
plt.ylabel("life Expectancy")
plt.title("Highest Average Life expectancy in Top 10 highly populated country in Africa")
plt.show()

"""Amongst the top highly populated countries in Africa we can say that Algeria is the one which has the highest Life Expectancy

Top 10 Highest GDP in Africa
"""

t10pofgdpafrica_df = countryafricaa_df.sort_values(by='gdp_cap', ascending=False).head(10)
print(t10pofgdpafrica_df)
plt.figure(figsize=(12,6))
sns.barplot(data=t10pofgdpafrica_df,x='country', y='gdp_cap')
plt.xlabel("Continents")
plt.ylabel("GDP per Capita")
plt.title("Top 10 Countries having the Highest Average GDP in Africa")
plt.show()

"""Libya has the highest GDP in Africa which is about 12013

Highest Average GDP in highly populated countries of Africa
"""

t10pofcgdpcafrica_df = t10pofcafrica_df.sort_values(by='gdp_cap', ascending=False).head(10)
print(t10pofcgdpcafrica_df)
plt.figure(figsize=(12,6))
sns.barplot(data=t10pofcgdpcafrica_df,x='country', y='gdp_cap')
plt.xlabel("Continents")
plt.ylabel("GDP per Capita")
plt.title("Top 10 Countries having the Highest Average GDP in Africa")
plt.show()

"""South africa has the highest GDP amongst the highly populated countries of Africa

Analysis on Oceania Region
"""

countryoceania_df = data_df.loc[data_df['continent']=='Oceania']
countryoceania_df.head(5)

countryoceania_df['country'].unique()

"""We have two countries that is Australia and New Zealand"""

countryoceaniaa_df=countryoceania_df.groupby('country')[['life_exp', 'gdp_cap', 'population']].aggregate({'life_exp': 'mean', 'gdp_cap': 'mean','population': 'mean' })
countryoceaniaa_df.head(5)

"""Highly populated country in Oceania"""

t10pofcoceania_df = countryoceaniaa_df.sort_values(by='population', ascending=False)
print(t10pofcoceania_df)
plt.figure(figsize=(12,6))
sns.barplot(data=t10pofcoceania_df,x='country', y='population')
plt.xlabel("Continents")
plt.ylabel("Population")
plt.xticks(rotation=30)
plt.title("Population in Each Country across Oceania")
plt.show()

"""We can see that Australia has the highest population Fourteen million, six hundred forty-nine thousand, three hundred ten.

Highest Average Life expectancy
"""

t10poflifeexpoceania_df = countryoceaniaa_df.sort_values(by='life_exp', ascending=False)
print(t10poflifeexpoceania_df)
plt.figure(figsize=(12,6))
sns.barplot(data=t10poflifeexpoceania_df,x='country', y='life_exp')
plt.xlabel("Continents")
plt.ylabel("life Expectancy")
plt.title("Top 10 Countries having the Highest Average life expectancy in Oceania")
plt.show()

"""Average life expectancy is almost similar but australia has the upper hand of 74.662917

Highest GDP in Oceania
"""

t10pofgdpoceania_df = countryoceaniaa_df.sort_values(by='gdp_cap', ascending=False).head(10)
print(t10pofgdpoceania_df)
plt.figure(figsize=(12,6))
sns.barplot(data=t10pofgdpoceania_df,x='country', y='gdp_cap')
plt.xlabel("Continents")
plt.ylabel("GDP per Capita")
plt.title("Top 10 Countries having the Highest Average GDP in Oceania")
plt.show()

"""Australia has the highest Average GDP in the Oceania region which is about 19980"""